// client/src/views/Login.vue
<template>
  <div class="container">
      <div class="field">
        <p class="control has-icons-left has-icons-right">
            <input class="input" type="email" placeholder="Email">
            <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
            </span>
            <span class="icon is-small is-right">
            <i class="fas fa-check"></i>
            </span>
        </p>
        </div>
        <div class="field">
        <p class="control has-icons-left is-primary">
            <input class="input" type="password" placeholder="Password">
            <span class="icon is-small is-left">
            <i class="fas fa-lock"></i>
            </span>
        </p>
        </div>
        <div class="field">
        <p class="control">
            <button class="button is-success">
            Login
            </button>
        </p>
        </div>
  </div>
</template>

<script>
export default {
}
</script>

<style>
</style>

// my-react-app/src/views/Login.jsx
import React from 'react';
export default function LoginComponent(){

    const error = "No Error";

    function login(e){
        e.preventDefault();
    }
    function google_login(e){
            e.preventDefault();
    }
    }
    return(
        <form className="container" onSubmit={login}>
      {error}
      <div className="field">
        <p className="control has-icons-left has-icons-right">
            <input className="input" type="email" placeholder="Email" v-model="email" />
            <span className="icon is-small is-left">
            <i className="fas fa-envelope"></i>
            </span>
            <span className="icon is-small is-right">
            <i className="fas fa-check"></i>
            </span>
        </p>
        </div>
        <div className="field">
        <p className="control has-icons-left">
            <input className="input" type="password" placeholder="Password" v-model="password"/>
            <span className="icon is-small is-left">
            <i className="fas fa-lock"></i>
            </span>
        </p>
        </div>
        <div className="field">
        <p className="control">
            <button className="button is-success">
            Login
            </button>
        </p>
        <button className="button is-primary" onClick="google_login" >
                Login with Google
            </button>
        </div>
  </form>
    )
}
