// my-react-app/src/components/Nav.jsx
import React from 'react';
import logo from '../logo.svg';
export default function Nav(){
    return(
        <h1 className = "title is-1">
            <img src={logo} "className="App-logo" alt="logo">     
        </h1>

        <nav className="navbar" role="navigation" aria-label="main navigation">
        <div className="navbar-brand">
          <a className="navbar-item" href="https://bulma.io">
            <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
          </a>
      
          <a className="{ 'is-active':isOpen }" @click="isOpen = !isOpen" role="button" className="navbar-burger burger" aria-label="menu" aria-expanded="false" >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div className="{ 'is-active':isOpen }" className="navbar-menu">
          <div className="navbar-start">
      
      
            <a router-link="" to="/" className="navbar-item" active-className="is-current" exact>Home</a>
            <a router-link="" to="/about" className="navbar-item" active-className="is-current">About</a>
            <a router-link="" to="/game" className="navbar-item" active-className="is-current">Game</a>
      
      
            <div className="navbar-item has-dropdown is-hoverable">
              <a className="navbar-link">
                More
              </a>
      
              <div className="navbar-dropdown">
                <a className="navbar-item">
                  About
                </a>
                <a className="navbar-item">
                  Jobs
                </a>
                <a className="navbar-item">
                  Contact
                </a>
                <hr className="navbar-divider">
                <a className="navbar-item">
                  Report an issue
                </a>
              </div>
            </div>
          </div>
      
          <div className="navbar-end">
            <div className="navbar-item">
            <div className="buttons">
            <a className="button is-primary">
                <strong>Sign up</strong>
            </a>
            <a className="button is-light" href="/login">
                Log in
            </a>
            </div>
            </div>
          </div>
        </div>
      </nav>
    );
}

// client/src/components/Nav.vue
<template>
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a :class="{ 'is-active':isOpen }" @click="isOpen = !isOpen" role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div :class="{ 'is-active':isOpen }" class="navbar-menu">
    <div class="navbar-start">


      <router-link to="/" class="navbar-item" active-class="is-current" exact>Home</router-link>
      <router-link to="/about" class="navbar-item" active-class="is-current">About</router-link>
      <router-link to="/game" class="navbar-item" active-class="is-current">Game</router-link>


      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <Login :CurrentUser="Currentuser"></Login>
      </div>
    </div>
  </div>
</nav>
</template>

<script>
import Login from "./LoginComponent"
import * as Users from "../models/Users"
export default {
  
  data: ()=>({
    isOpen: false,
    Users: Users
  }),
  components: {
    Login
  }
}
</script>

<style>
  .is-current {
    font-weight: bold;
    color: blueviolet
  }
</style>
